### ISSUE TITLE
Create DB schema and IBM CloudantDB instance

### ISSUE THREAD

**Issue by smithjilks** [QUALIS-LABS/IBM-Call-for-code-2021-zero-hunger-solution#7]
# Requirements
1. The DB schema should capture appropriate data of the following:
* Farmer Details
* Trader Details
* Driver Details
* Trip Information. 
** It should have the waypoints, destination, current location of driver, origin, truck plates, assigned driver id, status of the trip, etc
* Trader Requisition Details. 
** The produce, quantity, date of requisition, destination location, etc
* Farmer Collection/ Pick-up Requisition Details.
** You may need to capture  farmer id, produce type, quantity, date of request.

2. Refer to wire-frames for more details on the models you need to create.

# Tasks
- [x] Create DB schema
- [x] Create DB models with dummy data
- [ ] Create IBM CloudantDb instance.

**Comment by SammyOina** [comment]
services created in golang with rest API made with gin. DB made with postgres with gorm.

**Comment by SammyOina** [comment]
Main services tested and will be deployed

**Comment by SammyOina** [comment]
Services deployed to IBM Kubernetes service
