### ISSUE TITLE
Create an angular admin dashboard

### ISSUE THREAD

**Issue by smithjilks** [QUALIS-LABS/IBM-Call-for-code-2021-zero-hunger-solution#8]
# Requirements
1. The dashboard should allow the admin to:
* View all traders, farmers, requisitions, drivers, trips
* Create trips based on optimized routes, weather data and trader requisitions.
* View and respond to reported problems
* Send broadcast SMS and initiate push notifications to client apps
2. The dashboard should make good use of angular material.
3. The dashboard to make implement lazy loading of components and routes

# Tasks
- [ ] Create dashboard UI
- [ ] Create services for sending appropriate http requests 
- [ ] Populate dashboard with dynamic data
- [ ] Deploy complete site to IBM Cloud Object Storage
